name: travelcheck
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.8
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  font_awesome_flutter: ^10.7.0
  go_router: ^13.2.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon1024.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
