name: travelcheck
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.15.8
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  go_router: ^13.2.0
  google_nav_bar: ^5.0.6
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon1024.png"

flutter:
  uses-material-design: true
  fonts:
    - family: Cabin
      fonts:
        - asset: assets/fonts/Cabin-Regular.ttf
        - asset: assets/fonts/Cabin-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cabin-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cabin-Bold.ttf
          weight: 700
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/iconos/
